
- name: install apache and php for Ubuntu servers
  tags: apache2,ubuntu
  package:
    name:
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
    state: latest

- name: start apache2 service(Ubuntu)
  tags: apache2,service
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes

- name: copy default html file for site
  tags: apache2
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
